// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScreenRecordingConfig } from "./ScreenRecordingConfig";

export type RecordingConfig = { screen: ScreenRecordingConfig | null, };
