// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { ScreenRecordingBackend } from "./ScreenRecordingBackend";
import type { ScreenRecordingPermission } from "./ScreenRecordingPermission";
import type { ScreenRecordingPlatform } from "./ScreenRecordingPlatform";
import type { ScreenRecordingState } from "./ScreenRecordingState";

export type ScreenRecordingStatus = { state: ScreenRecordingState, paused: boolean, platform: ScreenRecordingPlatform, backend: ScreenRecordingBackend, permission: ScreenRecordingPermission, captureFps: number, retentionHours: number, storagePath: AbsolutePathBuf, capturedDisplayCount: number, newestFrameAt: bigint | null, lastError: string | null, };
